export interface Phase {
  id: number;
  key: string;
  label: string;
  icon: string;
  lifecycleFile: string;
  promptFile: string;
  checklistFile: string;
  agentFile: string;
}

export const PHASES: Phase[] = [
  {
    id: 0,
    key: "requirement",
    label: "00 · Requirement",
    icon: "$(list-ordered)",
    lifecycleFile: "docs/lifecycle/00-requirement.md",
    promptFile: "docs/prompts/00-requirement.md",
    checklistFile: "docs/checklists/00-requirement-checklist.md",
    agentFile: "docs/agents/requirement-agent.md",
  },
  {
    id: 1,
    key: "plan",
    label: "01 · Plan",
    icon: "$(milestone)",
    lifecycleFile: "docs/lifecycle/01-plan.md",
    promptFile: "docs/prompts/01-plan.md",
    checklistFile: "docs/checklists/01-plan-checklist.md",
    agentFile: "docs/agents/planning-agent.md",
  },
  {
    id: 2,
    key: "design",
    label: "02 · Design",
    icon: "$(symbol-structure)",
    lifecycleFile: "docs/lifecycle/02-design.md",
    promptFile: "docs/prompts/02-design.md",
    checklistFile: "docs/checklists/02-design-checklist.md",
    agentFile: "docs/agents/architecture-agent.md",
  },
  {
    id: 3,
    key: "code",
    label: "03 · Code",
    icon: "$(code)",
    lifecycleFile: "docs/lifecycle/03-code.md",
    promptFile: "docs/prompts/03-code.md",
    checklistFile: "docs/checklists/03-code-checklist.md",
    agentFile: "docs/agents/coding-agent.md",
  },
  {
    id: 4,
    key: "build",
    label: "04 · Build",
    icon: "$(tools)",
    lifecycleFile: "docs/lifecycle/04-build.md",
    promptFile: "docs/prompts/04-build.md",
    checklistFile: "docs/checklists/04-build-checklist.md",
    agentFile: "docs/agents/build-agent.md",
  },
  {
    id: 5,
    key: "test",
    label: "05 · Test",
    icon: "$(beaker)",
    lifecycleFile: "docs/lifecycle/05-test.md",
    promptFile: "docs/prompts/05-test.md",
    checklistFile: "docs/checklists/05-test-checklist.md",
    agentFile: "docs/agents/test-agent.md",
  },
  {
    id: 6,
    key: "secure",
    label: "06 · Secure & Comply",
    icon: "$(shield)",
    lifecycleFile: "docs/lifecycle/06-secure-comply.md",
    promptFile: "docs/prompts/06-secure-comply.md",
    checklistFile: "docs/checklists/06-secure-comply-checklist.md",
    agentFile: "docs/agents/security-agent.md",
  },
  {
    id: 7,
    key: "release",
    label: "07 · Release",
    icon: "$(tag)",
    lifecycleFile: "docs/lifecycle/07-release.md",
    promptFile: "docs/prompts/07-release.md",
    checklistFile: "docs/checklists/07-release-checklist.md",
    agentFile: "docs/agents/release-agent.md",
  },
  {
    id: 8,
    key: "deploy",
    label: "08 · Deploy",
    icon: "$(rocket)",
    lifecycleFile: "docs/lifecycle/08-deploy.md",
    promptFile: "docs/prompts/08-deploy.md",
    checklistFile: "docs/checklists/08-deploy-checklist.md",
    agentFile: "docs/agents/deploy-agent.md",
  },
  {
    id: 9,
    key: "operate",
    label: "09 · Operate",
    icon: "$(gear)",
    lifecycleFile: "docs/lifecycle/09-operate.md",
    promptFile: "docs/prompts/09-operate.md",
    checklistFile: "docs/checklists/09-operate-checklist.md",
    agentFile: "docs/agents/ops-agent.md",
  },
  {
    id: 10,
    key: "monitor",
    label: "10 · Monitor & Observe",
    icon: "$(graph)",
    lifecycleFile: "docs/lifecycle/10-monitor-observe.md",
    promptFile: "docs/prompts/10-monitor-observe.md",
    checklistFile: "docs/checklists/10-monitor-observe-checklist.md",
    agentFile: "docs/agents/observability-agent.md",
  },
  {
    id: 11,
    key: "incident",
    label: "11 · Incident & Learn",
    icon: "$(warning)",
    lifecycleFile: "docs/lifecycle/11-incident-learn.md",
    promptFile: "docs/prompts/11-incident-learn.md",
    checklistFile: "docs/checklists/11-incident-learn-checklist.md",
    agentFile: "docs/agents/incident-agent.md",
  },
];
